# Prometheus configuration for your blog analytics
# Add this to your existing prometheus.yml or create a new job

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Your existing jobs...
  
  # Blog API metrics
  - job_name: 'blog-api'
    static_configs:
      - targets: ['your-blog-api-domain.com:3000']  # Replace with your API domain
    scrape_interval: 15s
    metrics_path: '/metrics'
    scheme: 'https'  # or 'http' if not using HTTPS

  # Blog frontend metrics (via Pushgateway)
  - job_name: 'blog-frontend'
    static_configs:
      - targets: ['your-pushgateway-domain.com:9091']  # Replace with your Pushgateway
    scrape_interval: 15s
    metrics_path: '/metrics'
    scheme: 'https'

  # Optional: System metrics from your blog server
  - job_name: 'blog-server'
    static_configs:
      - targets: ['your-blog-server.com:9100']  # Node exporter on your server
    scrape_interval: 30s

# Alerting rules for your blog
rule_files:
  - "blog-alerts.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Example alerting rules
---
# blog-alerts.yml
groups:
  - name: blog.rules
    rules:
      - alert: HighErrorRate
        expr: sum(rate(blog_errors_total[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Blog error rate is {{ $value }} errors per second"

      - alert: LowPageViews
        expr: sum(rate(blog_page_views_total[10m])) < 0.01
        for: 10m
        labels:
          severity: info
        annotations:
          summary: "Low page view activity"
          description: "Blog page views are unusually low: {{ $value }} views per second"

      - alert: HighPageLoadTime
        expr: histogram_quantile(0.95, sum(rate(blog_page_load_time_seconds_bucket[5m])) by (le)) > 3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow page load times"
          description: "95th percentile page load time is {{ $value }} seconds"
